# https://taskfile.dev

version: "3"

vars:
  GREETING: gotail tasks
  targetbin: ~/bin
  buildname: gotail

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  test:
    desc: run tests
    cmds:
      - cmd: go test -v ./...
  clearbin:
    desc: clear build in bin dir
    cmds:
      - cmd: rm {{.targetbin}}/{{.buildname}}
        ignore_error: true
  copy:
    desc: copy build file to local bin
    dir: .
    preconditions:
      - test -d {{.targetbin}}/
    cmds:
      - task: build
      - task: clearbin
      - cp ./{{.buildname}} {{.targetbin}}/{{.buildname}}
      - rm ./{{.buildname}}
  build:
    desc: build to native architecture and OS
    cmds:
      - GOOS={{OS}} GOOARCH={{ARCH}} go build -ldflags="-s -w" -o {{.buildname}}{{exeExt}}
  macosarm:
    desc: build for macos ARM
    cmds:
      - GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o {{.buildname}}{{exeExt}}
      - file ./{{.buildname}}
  macosamd:
    desc: build for macos AMD
    cmds:
      - GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o {{.buildname}}{{exeExt}}
      - file ./{{.buildname}}
  windowsamd:
    desc: build for Windows
    cmds:
      - GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o {{.buildname}}{{exeExt}}
      - file ./{{.buildname}}
